# Use postgres/example user/password credentials
version: '3.1'

services:
  redis:
    container_name: mycurrency_redis_container
    # uts: host
    image: redis:latest
    restart: always
    ports: 
      - ${REDIS_PORT}:6379
    networks:
      - my-currency-bridge

  postgres-db:
    container_name: mycurrency_postgres_container
    # uts: host
    image: postgres:bookworm
    restart: always
    environment:
      POSTGRES_USER_FILE: /run/secrets/db_root_user
      POSTGRES_PASSWORD_FILE: /run/secrets/db_root_password
      POSTGRES_DB_FILE: /run/secrets/db_name
    secrets:
      - db_root_password
      - db_root_user
      - db_name
    ports:
      - ${POSTGRES_DB_PORT}:5432
    networks:
      - my-currency-bridge
    #volumes:
    #  - ./initdb-scripts:/docker-entrypoint-initdb.d

  pgadmin:
    container_name: mycurrency_pgadmin4_container
    # uts: host
    image: dpage/pgadmin4:latest
    restart: always 
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PG4ADMIN_EMAIL}
      PGADMIN_DEFAULT_PASSWORD_FILE: /run/secrets/pgadmin_root_password
    secrets:
      - pgadmin_root_password
    ports:
      - ${PG4ADMIN_PORT}:80
    networks:
      - my-currency-bridge

networks:
  my-currency-bridge:
    driver: bridge

secrets:
  db_root_password:
    file: ./secrets/pgsql/root_password.txt
  db_root_user:
    file: ./secrets/pgsql/root.txt
  db_name:
    file: ./secrets/pgsql/database_name.txt
  pgadmin_root_password:
    file: ./secrets/pgadmin/root_password.txt