# Generated by Django 5.2 on 2025-04-06 16:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("mycurrency_exchange_rates", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ExchangeRateProvider",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "provider_name",
                    models.CharField(db_index=True, max_length=50),
                ),
                ("provider_url", models.URLField()),
                ("priority", models.IntegerField()),
                ("active_flag", models.BooleanField(default=False)),
            ],
            options={
                "ordering": ["-priority"],
            },
        ),
    ]
