# Generated by Django 5.2 on 2025-04-07 16:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("mycurrency_exchange_rates", "0002_exchangerateprovider"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="exchangerateprovider",
            name="provider_url",
        ),
        migrations.AddField(
            model_name="exchangerateprovider",
            name="active_status",
            field=models.BooleanField(default=False),
        ),
    ]
