# Generated by Django 5.2 on 2025-04-07 16:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "mycurrency_exchange_rates",
            "0003_remove_exchangerateprovider_provider_url_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="exchangerateprovider",
            name="provider_name",
            field=models.CharField(db_index=True, max_length=50, unique=True),
        ),
    ]
